### ISSUE TITLE
Pushbullet and NMA notifications not being sent in unRAID

### ISSUE THREAD

**Issue by tooviral** [linuxserver/docker-tautulli#1]
As above.   No mention of anything in logs for either.

**Comment by lonix** [comment]
So i signed up for Pushbullet, and added configs into plexPy, then after start\stopping a episode, i get a error message, like so:

PushBullet request failed: Bad Request

So i whent pack into settings and looked over them again, and hit save. THen notifications started appering on my phone. allthough abit slow. i am unable to test NMA as i do not own souch a device.

**Comment by lonix** [comment]
All of my tests are a sucess. Need more information to help you mate. :)

**Comment by tooviral** [comment]
see http://lime-technology.com/forum/index.php?topic=42435.msg412689#msg412689

All good
