### ISSUE TITLE
Unable to set http_root

### ISSUE THREAD

**Issue by cullenmcdermott** [linuxserver/docker-tautulli#10]
Plexpy doesn't support a way of setting http_root via the ui so the only way to configure this is by editing the config.ini, however whenever the container is restarted this config file is reset. Being able to set the http_root would allow us to use this with a reverse proxy.

**Comment by ironicbadger** [comment]
Just curious... What does `http_root` give you and why do you need it?

**Comment by cullenmcdermott** [comment]
It lets me set the base url to something like http://myhostname:8181/plexpy which then lets me use it with my reverse proxy. See [this issue](https://github.com/drzoidberg33/plexpy/issues/49) for more details. And according to [this](https://github.com/drzoidberg33/plexpy/wiki/Frequently-Asked-Questions-%28FAQ%29#cat1-q2) I think we also need to be able to set http_proxy to 1

**Comment by zaggash** [comment]
@cullenmcdermott Actually it works.

You have to stop the app before editing the config file.
This is related to python not the Container :)

Enjoy

**Comment by zaggash** [comment]
@IronicBadger, You can close the Issue, I tested it and it works.

**Comment by cullenmcdermott** [comment]
That works. Thanks!
