### ISSUE TITLE
Make requests module part of the image

### ISSUE THREAD

**Issue by amigthea** [linuxserver/docker-tautulli#107]
## Desired Behavior
I need to use a very [useful script](https://github.com/blacktwin/JBOPS/tree/master/killstream) that requires the requests module installed, could be it implemented in the image?

## Current Behavior
requests module need to be installed manually

**Comment by aptalca** [comment]
You can add it via a custom script:
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by pannal** [comment]
(this might be something completely different) 

`TAUTULLI_URL` isn't get passed to `os.environ`: https://github.com/blacktwin/JBOPS/issues/289

**Comment by drizuid** [comment]
Solution was provided to OP, closing
