### ISSUE TITLE
disk I/O error?

### ISSUE THREAD

**Issue by johnny2678** [linuxserver/docker-tautulli#13]
Hi,
running this in a boot2docker VM and getting the following error after creating a fresh container.  Any idea what's going on? thx!

My docker run cmd:
`docker run -d --restart=unless-stopped --name=plexpy -h plexpy -v /mnt/docker/PlexPy/config:/config -e PGID=167609 -e PUID=167609 -p 6790:8181 linuxserver/plexpy`

I also get the same thing without the PGID/PUID vars.

```
22-Feb-2016 14:32:15 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 232, in <module>
    main()
  File "/opt/plexpy/PlexPy.py", line 160, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/__init__.py", line 188, in initialize
    plextv.refresh_users()
  File "/opt/plexpy/plexpy/plextv.py", line 31, in refresh_users
    monitor_db = database.MonitorDatabase()
  File "/opt/plexpy/plexpy/database.py", line 110, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
OperationalError: disk I/O error

Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 232, in <module>
    main()
  File "/opt/plexpy/PlexPy.py", line 160, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/__init__.py", line 188, in initialize
    plextv.refresh_users()
  File "/opt/plexpy/plexpy/plextv.py", line 31, in refresh_users
    monitor_db = database.MonitorDatabase()
  File "/opt/plexpy/plexpy/database.py", line 110, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
sqlite3.OperationalError: disk I/O error
22-Feb-2016 14:32:16 - INFO :: MainThread : Checking to see if the database has all tables....
22-Feb-2016 14:32:16 - ERROR :: MainThread : Can't connect to the database: disk I/O error
```

**Comment by sparklyballs** [comment]
sqlite is picky about hard links
either that or permissions, if in doubt, it's always permissions..

**Comment by johnny2678** [comment]
Some more info:

Container starts with no errors, I can progress through the wizard, default config files (config.ini, plexpy.db,etc) are all created and then the above error starts looping.

From the container, `docker exec -it plexpy bash`, all folders/files under config have 777 permissions.

I'm stumped...

edit: clarification

**Comment by sparklyballs** [comment]
then it's down to sqlite and it's finickity handling of hard links etc.

**Comment by johnny2678** [comment]
ok, I'm lost... Built a new image from git and got the following:

```
Fetched 22.0 MB in 26s (842 kB/s)
Reading package lists...
*** Running /etc/my_init.d/30_install_update_plexpy.sh...
*** /etc/my_init.d/30_install_update_plexpy.sh failed with status 127

*** Killing all processes...
```

Will try to build manually from baseimage to see if I can isolate...

**Comment by johnny2678** [comment]
Building manually from baseline worked but now I'm right back to the disk I/O error... any suggestions?

**Comment by sparklyballs** [comment]
yeah, it probably isn't going to work on a boot2docker VM because of sqlite.

**Comment by JeremyKennedy** [comment]
I'm sorry for commenting on an old issue, but @sparklyballs are you saying that I can't have PlexPy in Docker on Windows because of the way sqlite handles hard links?

**Comment by j0nnymoe** [comment]
@JeremyKennedy As far as I know, @sparklyballs was talking about "boot2docker" the old way of running docker on windows. In theory, it should work on the new Docker for windows beta.

**Comment by lonix** [comment]
@j0nnymoe that is still a boot2docker thing, it still uses a linux vm.

**Comment by j0nnymoe** [comment]
@JeremyKennedy as @lonix has stated above, it's no different, ignore my comment.

**Comment by bfeist** [comment]
Any word on this? Just ran into the same thing.

**Comment by j0nnymoe** [comment]
@bfeist could you provide some more details such as host os information/docker version etc please?

Thanks

**Comment by bfeist** [comment]
@j0nnymoe The Docker version is 1.13.1. Host is Windows 10 sp1 using Kitematic with boot2docker headless virtualbox. Any attempt to map the /config folder locally causes crashing. When I allow that to be housed within the container it works.

**Comment by j0nnymoe** [comment]
@bfeist sounds like something that boot2docker does to bridge the VM and Windows which is upsetting plexpy itselt. Unfortunately there isn't much I can suggest other than trying it on a linux house with the same setup. We don't test any of our containers on windows platforms so if any of them work within a windows environment, its a bonus. Sorry I couldn't be of much more help.

**Comment by bfeist** [comment]
@j0nnymoe Thanks for looking into it. I know Docker for Windows isn't ideal. Thanks for your hard work to put this out there.

**Comment by desimaniac** [comment]
This issue exists for older macs that have to use Kitematic/Docker Toolbox which also relies on boot2docker.
