### ISSUE TITLE
Unable to change config

### ISSUE THREAD

**Issue by firsttris** [linuxserver/docker-tautulli#17]
Hello,

i'm not able to change to config of plexpy using settings - it always changing back to its originale values.

I have started the container the following way:

docker run \
    --name="plexpy" \
    --restart=always \
    --net=host \
    -v /etc/localtime:/etc/localtime:ro \
    -v /media/red/docker/plexpy:/config \
    -v /media/red/docker/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/logs:ro \
    -e PUID=0 \
    -e PGID=0 \
    -d linuxserver/plexpy

settings pms ip form 0.0.0.0 to 192.168.10.12 and click save doesnt work.

changing config file directly does also not work.

please advise

regards
tristan

**Comment by zaggash** [comment]
Like a lot of python project, stop the application/container, edit the config and then restart.

**Comment by firsttris** [comment]
stop the application/container, edit the config and the restart.
=> does also reset the config to vanilla

for me it was working to restart plexpy from plexpy... after i completed the wizard plexpy is working!

:+1: 

thx for your help
