### ISSUE TITLE
It never starts

### ISSUE THREAD

**Issue by spacecakes** [linuxserver/docker-tautulli#22]
Hi,

I cant get it to run on Docker in DSM 6.0. The container never goes beyond this:

`remote: Compressing objects:   0% (1/330)   [K
`

Any ideas?

**Comment by CHBMB** [comment]
Not based on the information you've given, perhaps if you used the template we'd be able to help a little more.

**Comment by spacecakes** [comment]
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)





DSM 6.0 operating system, inside Docker on Docker port 8200 (real port 8181)



Container parameters:
PGID=101
PUID=0



Logs as pasted above. Never boots up. 







## Thanks, team linuxserver.io

**Comment by sparklyballs** [comment]
you need to tell us where this `remote: Compressing objects: 0% (1/330) �[K` is seen
we have no way of knowing if this is a synology issue or something to do with our image.

because generaly we do not see any messages similar to that.

**Comment by spacecakes** [comment]
It's seen when I start the container inside Docker. Here's the full log. 
[PlexPy.html.zip](https://github.com/linuxserver/docker-plexpy/files/546476/PlexPy.html.zip)

It just stays there.

**Comment by CHBMB** [comment]
You know the log has just shown it's passed that point....

**Comment by spacecakes** [comment]
I thought that too at first, but it's just in reverse order when exported.

**Comment by spacecakes** [comment]
And just like that, after waiting 30 minutes it booted up. Sorry for wasting your time.

**Comment by CHBMB** [comment]
As an aside, your PGID isn't actually 101 if you check the log....

**Comment by spacecakes** [comment]
That may very well be the case. I have no idea what that even is. I just [followed a guide](http://drfrankenstein.co.uk/2016/04/11/setting-up-couchpotato-in-docker-on-a-synology-nas/) to two of your other containers and applied the same logic here.
