### ISSUE TITLE
ython: can't open file '/opt/plexpy/PlexPy.py': [Errno 2]

### ISSUE THREAD

**Issue by casperse** [linuxserver/docker-tautulli#23]
I am using Synology Docker station. and sofar it have been rock solid.
After the last update of the Plexpy container I keep getting this error:
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory stderr 19:52:37
(Python should be part of the container I dont have Python locally installed on the server)

[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)

Host OS: Synology latest DSM

docker run \
--name="linuxserver-plexpy1" \
-p 8183:8181 \
--volume=/etc/localtime:/etc/localtime:ro \
--volume=/volume1/docker/timezone:/etc/timezone:ro \
--volume=/volume1/docker/plexpy/config:/config \
--volume="/volume1/Plex/Library/Application Support/Plex Media Server/Logs":/logs:ro \
-e PUID=1041 \
-e PGID=100 \
--restart=always \
--detach \
linuxserver/plexpy

UI install: https://forum.synology.com/enu/viewtopic.php?t=103804

python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory stderr 19:52:37

Yes see above for timezone txt file.

I also tried using the UI and that have worked before, but now gives the same error.

UI: Install: https://forum.synology.com/enu/viewtopic.php?t=103804

**Comment by casperse** [comment]
Ping...

**Comment by aptalca** [comment]
It could be a permissions issue. Make sure that the config folder is owned/accessible by the user id 1041

Can you also post the full log?

**Comment by sparklyballs** [comment]
could also be an incomplete pull on the first startup and an "impatient" restart.

**Comment by casperse** [comment]
I have pulled the container 4 times, and the folder permissions to the config folder is correct.

**Comment by sparklyballs** [comment]
well let's eliminate the first unusual thing i've noticed..

you have 
`--volume=/etc/localtime:/etc/localtime:ro \
--volume=/volume1/docker/timezone:/etc/timezone:ro`

you should only have `--volume=/etc/localtime:/etc/localtime:ro \`

**Comment by casperse** [comment]
I have removed all timezone settings from the install (I have installed it 8 times now) and always get the same error in th log: python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory stderr

**Comment by sparklyballs** [comment]
i've installed it many times and never seen that error, whatever it is, it's either peculiar to you or synology.

**Comment by casperse** [comment]
Actually I made a textfile in /volume1/docker/timezone containing just my TZ, so I think its okay?

**Comment by sparklyballs** [comment]
take it out and use `-e TZ=<timezone>`

**Comment by casperse** [comment]
FYI: Finally found the problem, and yes this is a Synology problem, but specific to this container (The others I have is working fine), it seems that even if I have a FW rule that allows the container access, it blocks "other things?" I have tested this by disabling my firewall and then it works perfectly. So I have created a Synology ticket for this problem. Thanks for the input, much appreciated.

**Comment by sparklyballs** [comment]
i'm going to close this as the issue lies elsewhere rather than this image.
