### ISSUE TITLE
installed Plexpy on Freenas 10 via docker

### ISSUE THREAD

**Issue by seed1234** [linuxserver/docker-tautulli#31]
Cannot connect to PlexPy Gui
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

FreeNAS 10

docker@box:~$ docker logs -f plexpy
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory
python: can't open file '/opt/plexpy/PlexPy.py': [Errno 2] No such file or directory

**Comment by sgtsquiggs** [comment]
I have the same problem on my QNAP (x86-64). Seems the problem is that https connections fail:

```
root@58fb08dc3b93:/root$ curl -v https://github.com/
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
Killed
```
```
root@58fb08dc3b93:/root$ curl -v https://google.com/
*   Trying 172.217.10.142...
* TCP_NODELAY set
* Connected to google.com (172.217.10.142) port 443 (#0)
Killed
```

**Comment by j0nnymoe** [comment]
@seed1234 Could you provide some more information about the value's you used when setting up plex on freenas please? (screenshots will do)

@sgtsquiggs QNAP issues are known and something we will get working on once we have a QNAP device up and running.

**Comment by j0nnymoe** [comment]
@seed1234 re-reading your error log's. I'm guessing that this is due to not setting a PGID/PUID as the docker containers default to 911 when nothing is specified.

@sgtsquiggs Please see my post here: https://github.com/linuxserver/docker-plexpy/issues/29#issuecomment-292290379 I got plexpy running on our QNAP TS-251A with no problems last night.

**Comment by j0nnymoe** [comment]
As no reply for two weeks on this issue, I am assuming this has now been resolved.
Please reopen if not the case.
