### ISSUE TITLE
Newest Plexpy v2 branch requires PyCryptodome to be installed

### ISSUE THREAD

**Issue by wcomartin** [linuxserver/docker-tautulli#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Newest Plexpy v2 branch requires PyCryptodome to be installed

This is used for notification encryption for the android app @JonnyWong16 and I are developing

Installation Instructions:
http://pycryptodome.readthedocs.io/en/latest/src/installation.html

**Comment by JonnyWong16** [comment]
`pycryptodomex` preferred.

**Comment by CHBMB** [comment]
I'm sure @sparklyballs will be along later to tell me what I've done wrong, but here's a start.
