### ISSUE TITLE
Suggestion on how to call commands outside the container

### ISSUE THREAD

**Issue by mikethecalamity** [linuxserver/docker-tautulli#39]
I would like to use the scripts agent to call a script to close specific resource intensive processes on my Synology NAS when things on Plex begin to be watched. This is easy to do from a script using the command "/usr/syno/bin/synopkg stop <process name>". Do you have a suggestion of how to be able to call this executable without getting a " No such file or directory" error?

**Comment by aptalca** [comment]
From inside the docker container, you can telnet or ssh into the host machine/computer to run the commands
