### ISSUE TITLE
Mechanism to chose PlexPy git branch

### ISSUE THREAD

**Issue by krohrsb** [linuxserver/docker-tautulli#4]
Say i want to run develop instead of master. Could we add a ENV variable to allow this?

**Comment by lonix** [comment]
Should be fairly easy to do, Ill add this to things to look into when i have some spare time.

**Comment by JigSawFr** [comment]
:+1:  could be a great enhancement !

**Comment by zaggash** [comment]
#11

**Comment by zaggash** [comment]
#16
