### ISSUE TITLE
DNS issues running plexpy in Kubernetes

### ISSUE THREAD

**Issue by vistalba** [linuxserver/docker-tautulli#42]
I run the plexpy docker inside kubernetes cluster in my LAN network. I can't resolv external DNS names. I figured out the following with tcpdump:

If I do nslookup in the container for: google.com it makes a DNS request to google.com.internal.domain.com -> doesn't exist.

If I remove the "internal.domain.com" from /etc/resolve.conf as a seach domain the problem is gone.

I don't know, why it happens... 

https://hub.docker.com/r/linuxserver/plexpy/
	

Ubuntu 16.04 LTS with Kubernetes 1.8.3 (Issue is persistend since kubernetes 1.7)

**Comment by thelamer** [comment]
This has nothing to do specifically with this container. Docker containers inherit their DNS from the host on bridged networks. In Kubernetes you can customize DNS settings for your services and pods: 

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
