### ISSUE TITLE
Error response from daemon: error while creating mount source path

### ISSUE THREAD

**Issue by bensternthal** [linuxserver/docker-tautulli#44]
Pretty stumped on this one.. should be easy-peasey. After running the docker create command and the docker start I get the following error:

```
Error response from daemon: error while creating mount source path '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs': mkdir /var/lib/plexmediaserver: permission denied
Error: failed to start containers: plexpy
```
Spidey sense is that the docker user cannot access the plex logs location. Which seems odd. I have tried a few things to debug including messing with the user and group ids, but nothing I try works. I've confirmed that as my user I can read and edit files there no problem.

Appreciate any help you can provide.

### Host OS 

Ubuntu 17.10

### Docker Commands

``` 
docker create \ 
--name=plexpy \
-v /home/ben/Media-Server/plexpy:/config \
-v /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro \
-e PGID=1000 -e PUID=1000  \
-e TZ=America/Los_Angeles \
-p 8181:8181 \
linuxserver/plexpy
```

```
docker start plexpy
```

### Docker Output

```
Error response from daemon: error while creating mount source path '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs': mkdir /var/lib/plexmediaserver: permission denied
Error: failed to start containers: plexpy
```

### Notes

1. Plex is installed in the default manner. Log location is owned by plex:plex
2. User id and group are of my user.
3. I am able to edit and delete content in the log location.

**Comment by j0nnymoe** [comment]
Wrap the second volume mount in " 's and this will get past the error.

**Comment by bensternthal** [comment]
Unfortunately that did not work. I tried both:

```
"/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs"
```
and 

```
"/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs"
```

**Comment by tobbenb** [comment]
Are you sure the path is correct? The error say that it can't create the source path. That probably means that the path doesn't exist and it tries to create it.

**Comment by bensternthal** [comment]
Yep path is correct, can copy paste into terminal and cd into that dir.

Something is funky with docker and perms. It seems to not be able to access anything outside my home directory.

Grrr!

**Comment by bensternthal** [comment]
OK i think I sorted this.

The issue was using docker-snap https://github.com/docker/docker-snap/blob/master/README.md

Yeah I should have known better. Installing docker-ce via the official docs seems to have worked.

Thanks again for helping.

**Comment by srslynow** [comment]
@bensternthal thank you so much for coming back with the answer! I was going crazy, turned out the system I was working on had docker snap installed as well.

**Comment by jimtaylor123** [comment]
thanks

**Comment by JGNi** [comment]
How do you uninstall it? Can't see the option in dpkg or apt-get remove

**Comment by bensternthal** [comment]
@JGNi Can you create a new issue? It sounds like you are experiencing something different from what is described here.

**Comment by JGNi** [comment]
I found the solution now. I didn't know about snap. I do now.

**Comment by PuZZleDucK** [comment]
Commands to remove docker snap and install docker via apt:
```
sudo snap remove docker
sudo apt install docker
```

**Comment by thelamer** [comment]
@PuZZleDucK never install from OS repos always use docker ce repos: 

https://docs.docker.com/install/linux/docker-ce/ubuntu/
