### ISSUE TITLE
How to use this with linuxserver/plex

### ISSUE THREAD

**Issue by ShakataGaNai** [linuxserver/docker-tautulli#52]
So the instructions on tautulli specify mounting the plex log directory, however https://github.com/linuxserver/docker-plex doesn't appear to have that as an option. So what configuration is required for these two linuxserver images to operate together?

**Comment by aptalca** [comment]
It's in the readme here: https://github.com/linuxserver/docker-tautulli/blob/master/README.md
You need to map the plex log location on your server in this container's settings
`-v <path to plex logs>:/logs:ro` so if plex is at /opt/plex on your machine, then set it to `-v "/opt/plex/Library/Application Support/Plex Media Server/Logs":/logs:ro`
That way you can reach that location at `/logs` inside this container

**Comment by ShakataGaNai** [comment]
So you're saying this doesn't work with the liunxserver/plex image.

**Comment by j0nnymoe** [comment]
It does work with our container. Point `/logs` to the logs folder within your Plex appdata on your host.

**Comment by aptalca** [comment]
Plex logs are under the /config folder you map for the plex container
