### ISSUE TITLE
Scripts triggered by Tautulli require JSON parsing - Request to add 'jq' to container

### ISSUE THREAD

**Issue by metaMMA** [linuxserver/docker-tautulli#56]
I would like to suggest adding [jq - a lightweight and flexible command-line JSON processor](https://stedolan.github.io/jq/) to the Tautulli docker container. There are quite a few scripts that can be triggered by Tautulli that require parsing through JSON. This can be done in the container now using other tools. But the currently available tools aren't efficient and not made for the job. Kind of like hammering in a nail with a pipe-wrench. Adding jq would allow for easy parsing and would come in handy, because applications like sonarr and radarr output JSON with many of their API calls.  I think having this ability would help expand the possibilities of scripting and creating mutual relationships between these related applications. 

So functionality could be greatly be increased due to the ease of creating these scripts and, as a bonus, the application is *very* lightweight, so there is very little downside to adding it to the container. I am open to conversation on the topic, because perhaps there is another solution I am overlooking. Thanks for your time.

**Comment by homerr** [comment]
jq is now in the container, this was completed in pr #69
