### ISSUE TITLE
Tautulli containers unknown version installed

### ISSUE THREAD

**Issue by Rawh** [linuxserver/docker-tautulli#67]
Hi there,

I'm running the latest Tautulli container but each and every time I go to the webgui it tells me it has no idea what version it's running.

![image](https://user-images.githubusercontent.com/10486655/52309444-6eaf5000-29a0-11e9-907d-a192b785d164.png)

Some info about my rig:
Unraid Pro license
Version 6.6.6 (stable)

Running docker version: 18.06.1-ce
Container version: 
> docker inspect -f '{{ index .Config.Labels "build_version" }}' tautulli
> Linuxserver.io version:- v2.1.26-ls1 Build-date:- 2019-01-29T23:22:48+00:00

Image version: 
> docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/tautulli
> Linuxserver.io version:- v2.1.26-ls1 Build-date:- 2019-01-29T23:22:48+00:00

Docker logs: https://pastebin.com/PBajcyQi (expire 1 week)

**Comment by aptalca** [comment]
Thanks, we are aware and a fix is on the way

**Comment by aptalca** [comment]
@Rawh I think we fixed this a long time ago, but forgot to close this issue. Can you confirm that it is fixed in the latest version and if so, close the ticket?

**Comment by Rawh** [comment]
Yep yep. It's been good for a long time, you can close it 👍

**Comment by aptalca** [comment]
Thanks for the confirmation
