### ISSUE TITLE
HTTPS: SSL disabled

### ISSUE THREAD

**Issue by LennyM8472** [linuxserver/docker-tautulli#7]
Hi,

would be great if you can add the pyOpenSsl module to the container

I'm getting following error message when enabling https "The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled."

thanks
Lenny

**Comment by zaggash** [comment]
Did someone test it ?

**Comment by sparklyballs** [comment]
not a plex user personally.

**Comment by zaggash** [comment]
#12
