### ISSUE TITLE
Add healthcheck support

### ISSUE THREAD

**Issue by Arcanemagus** [linuxserver/docker-tautulli#79]
In Tautulli v2.1.31 a new endpoint of `/status` was added that responds with a status check message allowing this to be used for health check purposes.

You can see how we are currently doing this in our official image [here](https://github.com/Tautulli/Tautulli-Docker/blob/a498f3e8a098b3b3234f17b57f533d618b8adb34/Dockerfile#L80).

Note that this will work whether the user has HTTPS enabled or not, whether the user has the API enabled or not, and redirects for different `HTTP Root` settings are handled automatically.

**Comment by aptalca** [comment]
Thanks for the heads up, we'll look into it.

**Comment by thelamer** [comment]
Just a heads up , this is something we have discussed internally in the past and please understand implementing health checks is something we would need to do Org-wide. 

As it stands right now this functionality while implemented from a code standpoint has not been integrated into Docker's own official images. 

My personal concern is it is functionality that will not see future support, especially because Kubernetes has their own health checking system with their probes system.

**Comment by Arcanemagus** [comment]
> As it stands right now this functionality while implemented from a code standpoint has not been integrated into Docker's own official images.

I'm not sure what you are talking about here with regards to "official images", the `docker` command definitely supports checking this, and there are many commands related to it:
![image](https://user-images.githubusercontent.com/427137/63281652-0819c180-c262-11e9-86e1-b053d3b56bec.png)

If you mean the official Tautulli images that we maintain it's absolutely been implemented there... that's why I was giving you guys the heads up about it 😕.

> My personal concern is it is functionality that will not see future support, especially because Kubernetes has their own health checking system with their probes system.

Maybe? That doesn't really have any bearing on this discussion though.

> Just a heads up , this is something we have discussed internally in the past and please understand implementing health checks is something we would need to do Org-wide.

That's an interesting choice to restrict individual images till it can be done for _all_ at once, but I'm not on your team so 🤷‍♂.

This issue was just meant as a friendly heads up that we implemented a (we think) good way within Tautulli to get this feature working, feel free to close it if you aren't going to take advantage of it 😉.

**Comment by thelamer** [comment]
I am specifically referencing Docker's own official images. 

https://hub.docker.com/search/?type=image&image_filter=official

REDIS, NGINX, Mysql, etc etc.

**Comment by thelamer** [comment]
This is the Maintainer of the official images:
https://github.com/docker-library/cassandra/pull/76#issuecomment-426816911

I do not see how we are going to get behind the HEALTHCHECK concept as an organization if Docker will not ever be implementing this functionality on their huge library of images with Billions of pulls. 

I am closing this , if this stance changes in the future from Docker as an Org than I think this is worth re-visiting. When big orgs are split on supporting a feature or application it has been my experience that they stop being supported and eventually get sunsetted.
