### ISSUE TITLE
https://github.com/Aquinas74/docker-tautulli/pull/1#issue-298637994

### ISSUE THREAD

**Issue by Aquinas74** [linuxserver/docker-tautulli#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by j0nnymoe** [comment]
what?

**Comment by aptalca** [comment]
looks like user error
