### ISSUE TITLE
Just a request

### ISSUE THREAD

**Issue by justinglock40** [linuxserver/docker-tautulli#85]
Can this be added to the Dockerfile for your next image build?

`pip install jsonrpclib-pelix`

There's a script made by BlackTwin that depends on this module to function. I've bash'd into the container and installed myself but whenever the container is restarted it gets removed. Thanks in advanced if you can make this possible.

**Comment by justinglock40** [comment]
this is the script: https://gist.github.com/Hellowlol/a5d0cab4bde185b38404

**Comment by aptalca** [comment]
Here's info on how you can customize our containers so the changes are persistent: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by justinglock40** [comment]
Thanks
