### ISSUE TITLE
Feature request: Healthcheck

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-tautulli#87]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
------------------------------

## Expected Behavior
Implement Healthcheck

## Current Behavior
No Healthcheck

## Steps to Reproduce
https://github.com/Tautulli/Tautulli-Docker/blob/master/Dockerfile

HEALTHCHECK --start-period=90s CMD curl -ILfSs http://localhost:8181/status > /dev/null || curl -ILfkSs https://localhost:8181/status > /dev/null || exit 1

**Comment by aptalca** [comment]
See the discussion here: https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-522371251
