### ISSUE TITLE
Add environment variable to disable telemetry

### ISSUE THREAD

**Issue by zx8** [linuxserver/docker-tautulli#93]
By default, Tautulli enables Google Analytics:

https://github.com/Tautulli/Tautulli/blob/7f178e091349a1399395c1ac3227d6f0fa801efc/plexpy/config.py#L632

According to [their FAQ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q21), it is possible to opt-out:

> If you would like to opt-out of data collection, you can set `system_analytics = 0` in the `config.ini` file. Tautulli must be shut down when editing the file.

It would be fantastic if an environment variable could be introduced to allow us to opt-out of this behaviour more easily.

**Comment by j0nnymoe** [comment]
Forgive my ignorance but if we added a variable to do that. Wouldn't we need to boot tautalli first then stop it, run a script to do the change then boot it again?

Imo if you're already configuring it, it's not much effort to do this aswell as it's just a one time thing.

You can add this in your own container of you want via this https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ or if you could submit a PR to do the work.

**Comment by zx8** [comment]
I'm not sure I follow – why would it be necessary to first start Tautulli, make the change, then boot it again, compared to just writing the config pre-boot and then starting Tautulli?

I'll take a look at your suggested solution.

**Comment by aptalca** [comment]
Because there is no config file until it runs. We sure aren't going to create a dummy config file for it just to disable telemetry because it will break the whole thing the moment tautulli makes a change to their config file format and we are out of step

**Comment by zx8** [comment]
Thanks for the clarification.

Given the situation, I don't think the Linuxserver Tautulli image is the correct place for this to be resolved, so have raised it with the upstream @ https://feathub.com/Tautulli/Tautulli/+459
