### ISSUE TITLE
Missing Pyopenssl

### ISSUE THREAD

**Issue by tobbenb** [linuxserver/docker-tautulli#94]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by jchonig** [comment]
I just noticed this myself.  I hacked around it by adding config/custom-cont-init.d/10-https:

```
#!/usr/bin/with-contenv bash

# Add dependencies
apk add --no-cache --virtual=build-dependencies py3-pip python3-dev gcc musl-dev libffi-dev openssl-dev

# Add pyopenssl
pip3 install --no-cache-dir -U pyopenssl

# Cleanup
apk del --purge build-dependencies
rm -rf /root/.cache /tmp/*

# Enable https
sed -i '/^\[General\]$/,/^\[/ s/^enable_https = 0/enable_https = 1/' /config/config.ini
```

If I get time I'll try to come up with a PR.
