### ISSUE TITLE
Remove Plex logs from installation instructions

### ISSUE THREAD

**Issue by JonnyWong16** [linuxserver/docker-tautulli#97]
Please remove the Plex logs volume bind from your installation instructions. This is causing too much confusion with users thinking the Plex logs are required for Tautulli to function when all it really adds is a log viewer functionality.

It has already been removed from our official installation instructions:

https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#docker

**Comment by aptalca** [comment]
@JonnyWong16 thanks for the heads up. I honestly thought they were still needed for tautulli to get historical data. It's removed now.
